[package]
name = "acir_field"
version = "0.4.1"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>"]
edition = "2021"
license = "MIT"
description = "The field implementation being used by ACIR."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"

ark-bn254 = { version = "^0.4.0", optional = true, default-features = false, features = [
    "curve",
] }
ark-bls12-381 = { version = "^0.4.0", optional = true, default-features = false, features = [
    "curve",
] }
ark-ff = { version = "^0.4.0", optional = true, default-features = false }
ark-serialize = { version = "^0.4.0", default-features = false }

blake2 = "0.9.1"
cfg-if = "1.0.0"
serde = { version = "1.0.136", features = ["derive"] }

num-bigint = "0.4"
num-traits = "0.2.8"

[features]
default = ["bn254"]
bn254 = ["ark-bn254", "ark-ff"]
bls12_381 = ["ark-bls12-381", "ark-ff"]
