default world acvm-wasm {
    export open-task: func(
        acir-bytes: list<u8>,
        initial-witness: list<tuple<u32, string>>,
    ) -> u32

    export step-task: func(task-id: u32) -> bool

    export get-blocker: func(task-id: u32) -> tuple<u32, list<string>>

    export unblock-task: func(task-id: u32, solution: list<string>)

    export close-task: func(task-id: u32) -> list<tuple<u32, string>>
}