default world acvm-wasm {
    // Returns: The task id of the new task
    export open-task: func(
        acir-bytes: list<u8>,
        initial-witness: list<tuple<u32, string>>,
    ) -> u32

    // Result::Ok: True if done
    export step-task: func(
        task-id: u32,
    ) -> result<bool, string>

    // Result::Ok: Name of black box with list of inputs
    export get-blocker: func(
        task-id: u32,
    ) -> option<tuple<string, list<string>>>

    export unblock-task: func(
        task-id: u32,
        solution: list<string>
    ) -> result<_, string>

    // Result::Ok: The solved intermediate witness
    export close-task: func(
        task-id: u32
    ) -> result<list<tuple<u32, string>>, string>
}