name: Publish acvm_js

on:
  push:
    tags:
      - "acvm_js-v*"

jobs:
  build-acvm-js-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build acvm-js
        run: |
          nix build .#

      - name: Discover Build Output Path
        run: echo "BUILD_OUTPUT_PATH=$(readlink -f ./result)" >> $GITHUB_ENV

      - name: Copy Build Output to Temporary Directory
        run: |
          mkdir temp_publish_dir
          cp -r ${{ env.BUILD_OUTPUT_PATH }}/* temp_publish_dir/

      - name: Publish to NPM
        working-directory: ./temp_publish_dir
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
