name: Tag Release Workflow

on:
  push:
    tags:
      - "acvm_js-v*"
    branches:
      - jb/acvm-js-publishing

jobs:
  build-acvm-js-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build acvm-js
        run: |
          nix build .#

      - name: Discover Build Output Path
        run: echo "BUILD_OUTPUT_PATH=$(readlink -f ./result)" >> $GITHUB_ENV

      - name: Copy Build Output to Temporary Directory
        run: |
          mkdir temp_publish_dir
          cp -r ${{ env.BUILD_OUTPUT_PATH }}/* temp_publish_dir/

      - name: Publish to NPM
        working-directory: ./temp_publish_dir
        # run: npm publish
        run: |
          npm pack
          tar -tzf *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
