name: Test acvm_js

on: [push, pull_request]

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-acvm-js-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: barretenberg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build acvm-js
        run: |
          nix build .#

      - name: Dereference symlink
        run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: acvm-js
          path: ${{ env.UPLOAD_PATH }}
          retention-days: 3

  test-acvm_js-node:
    needs: [build-acvm-js-package]
    name: Node.js Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: acvm-js
          path: ./result

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          working-directory: ./acvm_js

      - name: Run node tests
        working-directory: ./acvm_js
        run: yarn test

  test-acvm_js-browser:
    needs: [build-acvm-js-package]
    name: Browser Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: acvm-js
          path: ./result

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          working-directory: ./acvm_js

      - name: Install playwright deps
        working-directory: ./acvm_js
        run: |
          npx playwright install
          npx playwright install-deps

      - name: Run browser tests
        working-directory: ./acvm_js
        run: yarn test:browser

  test-acvm_js-rust:
    needs: [build-acvm-js-package]
    name: Rust Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: ubuntu
            runner: ubuntu-latest
            target: wasm32-unknown-unknown

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: acvm-js
          path: ./result

      - name: Set up test environment
        uses: ./.github/actions/setup
        with:
          working-directory: ./acvm_js

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@1.67.0
        with:
          targets: ${{ matrix.target }}

      - name: Install cargo
        working-directory: ./acvm_js
        run: cargo install --path .

      - name: Run rust tests
        working-directory: ./acvm_js
        run: yarn test:rust
